# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
is_compact <- function(x) {
    .Call(`_compact_is_compact`, x)
}

#' @export
compact_info <- function(x) {
    .Call(`_compact_compact_info`, x)
}

#' @export
compact_is_expanded <- function(x) {
    .Call(`_compact_compact_is_expanded`, x)
}

#' @export
compact_length <- function(x) {
    .Call(`_compact_compact_length`, x)
}

#' @export
compact_first <- function(x) {
    .Call(`_compact_compact_first`, x)
}

#' @export
compact_increment <- function(x) {
    .Call(`_compact_compact_increment`, x)
}

